project/__init__.py
import logging
import os
from logging.handlers import RotatingFileHandler

from flask import Flask, render_template
from flask.logging import default_handler


def create_app():
    # Create the Flask app
    app = Flask(__name__)

    # Configure the Flask app
    config_type = os.getenv('CONFIG_TYPE', default='config.DevelopmentConfig')
    app.config.from_object(config_type)

    register_blueprints(app)
    configure_logging(app)
    register_app_callbacks(app)
    register_error_pages(app)
    return app


def register_blueprints(app):
    # Import the blueprints
    from project.stats import stats_blueprint

    # Since the application instance is now created, register each Blueprint
    # with the Flask application instance (app)
    app.register_blueprint(stats_blueprint)


def configure_logging(app):
    # Logging Configuration
    file_handler = RotatingFileHandler('instance/meta-pawn.log',
                                       maxBytes=16384,
                                       backupCount=20)
    file_formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(filename)s:%(lineno)d]')
    file_handler.setFormatter(file_formatter)
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)

    # Remove the default logger configured by Flask
    app.logger.removeHandler(default_handler)

    app.logger.info('Starting Meta-Pawn...')


def register_app_callbacks(app):
    @app.before_request
    def app_before_request():
        app.logger.info('Calling before_request() for the Flask application...')

    @app.after_request
    def app_after_request(response):
        app.logger.info('Calling after_request() for the Flask application...')
        return response

    @app.teardown_request
    def app_teardown_request(error=None):
        app.logger.info('Calling teardown_request() for the Flask application...')

    @app.teardown_appcontext
    def app_teardown_appcontext(error=None):
        app.logger.info('Calling teardown_appcontext() for the Flask application...')


def register_error_pages(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    @app.errorhandler(405)
    def method_not_allowed(e):
        return render_template('405.html'), 405

project/stats/__init__.py
"""
The stats blueprint handles the main stats viewer of the application
"""
from flask import Blueprint

stats_blueprint = Blueprint('stats', __name__, template_folder='templates')

from . import routes

project/stats/routes.py
import pandas as pd
from flask import current_app, render_template, request

import app
from . import stats_blueprint


# request callbacks
@stats_blueprint.before_request
def stats_before_request():
    current_app.logger.info('Calling before_request() for the stats blueprint...')


@stats_blueprint.after_request
def stats_after_request(response):
    current_app.logger.info('Calling after_request() for the stats blueprint...')
    return response


@stats_blueprint.teardown_request
def stats_teardown_request(error=None):
    current_app.logger.info('Calling teardown_request() for the stats blueprint...')


@stats_blueprint.route('/_png_plot', methods=['GET', 'POST'])
def png_plot():
    current_app.logger.info('Calling the png_plot() function.')

    return render_template('stats/png_plot.html')


@stats_blueprint.route('/_opening_explorer', methods=['GET', 'POST'])
def opening_explorer():
    current_app.logger.info('Calling the opening_explorer() function.')

    df = app.uf.get_explorer_table()

    # get table headers and rows
    columns = df.columns
    rows = df.values

    # re-render html page with new table values
    return render_template('stats/opening_explorer.html',
                           columns=columns,
                           rows=rows)


@stats_blueprint.route('/_update_alternative_elo_table', methods=['GET', 'POST'])
def update_alternative_elo_table():
    elo = int(list(request.args.values())[0])
    white_value = list(request.args.values())[1] == 'true'

    # get new dataframe based on new elo value
    if white_value:
        df = app.uf.get_recommend_w(elo)
    else:
        df = app.uf.get_recommend_b(elo)

    # return the new table out to the client
    return pd.DataFrame(df).to_json(orient='columns')


@stats_blueprint.route('/_elo_opening_suggestion', methods=['GET', 'POST'])
def elo_opening_suggestion():
    current_app.logger.info('Calling the elo_opening_suggestion() function.')

    # re-render html page with new table values
    return render_template('stats/elo_opening_suggestion.html')


@stats_blueprint.route('/_update_opening_suggester_table', methods=['GET', 'POST'])
def update_opening_suggester_table():
    skill = int(list(request.args.values())[0])
    novelty = int(list(request.args.values())[1])
    white_value = list(request.args.values())[2] == 'true'

    # get new dataframe based on new elo value
    if white_value:
        df = app.uf.get_ad_recommend_w(skill, novelty)
    else:
        df = app.uf.get_ad_recommend_b(skill, novelty)

    # return the new table out to the client
    return pd.DataFrame(df).to_json(orient='columns')


@stats_blueprint.route('/_opening_suggester_page', methods=['GET', 'POST'])
def opening_suggester_page():
    current_app.logger.info('Calling the opening_suggester_page() function.')

    # re-render html page with new table values
    return render_template('stats/opening_suggester.html')


@stats_blueprint.route('/', methods=['GET', 'POST'])
def index():
    current_app.logger.info('Calling the index() function.')

    # re-render html page with new table values
    return render_template('stats/elo_opening_suggestion.html')

project/templates/405.html
{% extends "base.html" %}

{% block content %}
    <h1 class="errorpage-title">Method Not Allowed (405)</h1>
    <div class="errorpage-section">
        <h4>The requested method is not supported!</h4>
        <h4><a href="{{ url_for('stats.index') }}">Meta-Pawn</a></h4>
    </div>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">

    <!-- Bootstrap core CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <!-- Custom styles for this template-->
    <link href="{{ url_for('static', filename='css/navbar-top-fixed.css') }}" rel="stylesheet">

    <!-- Additional styling-->
    {% block styling %}
    {% endblock %}

    <!-- Include JQuery -->
    <script src="{{ url_for('static', filename='scripts/jquery.js') }}"></script>

    <!-- Make a global variable with the prefix to the root of the application -->
    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>

    <title>Meta-Pawn</title>
</head>
<body>

<!-- Bootstrap core JS (bundle w/ Popper)-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous">
</script>

<!-- Child template-->
{% block content %}
{% endblock %}
</body>
</html>