project/stats/__init__.py
"""
The stats blueprint handles the main stats viewer of the application
"""
from flask import Blueprint

stats_blueprint = Blueprint('stats', __name__, template_folder='templates')

from . import routes

project/stats/routes.py
import pandas as pd
from flask import current_app, render_template, request

import app
from . import stats_blueprint


# request callbacks
@stats_blueprint.before_request
def stats_before_request():
    current_app.logger.info('Calling before_request() for the stats blueprint...')


@stats_blueprint.after_request
def stats_after_request(response):
    current_app.logger.info('Calling after_request() for the stats blueprint...')
    return response


@stats_blueprint.teardown_request
def stats_teardown_request(error=None):
    current_app.logger.info('Calling teardown_request() for the stats blueprint...')


@stats_blueprint.route('/_png_plot', methods=['GET', 'POST'])
def png_plot():
    current_app.logger.info('Calling the png_plot() function.')

    return render_template('stats/png_plot.html')


@stats_blueprint.route('/_opening_explorer', methods=['GET', 'POST'])
def opening_explorer():
    current_app.logger.info('Calling the opening_explorer() function.')

    df = app.uf.get_explorer_table()

    # get table headers and rows
    columns = df.columns
    rows = df.values

    # re-render html page with new table values
    return render_template('stats/opening_explorer.html',
                           columns=columns,
                           rows=rows)


@stats_blueprint.route('/_update_alternative_elo_table', methods=['GET', 'POST'])
def update_alternative_elo_table():
    elo = int(list(request.args.values())[0])
    white_value = list(request.args.values())[1] == 'true'

    # get new dataframe based on new elo value
    if white_value:
        df = app.uf.get_recommend_w(elo)
    else:
        df = app.uf.get_recommend_b(elo)

    # return the new table out to the client
    return pd.DataFrame(df).to_json(orient='columns')


@stats_blueprint.route('/_elo_opening_suggestion', methods=['GET', 'POST'])
def elo_opening_suggestion():
    current_app.logger.info('Calling the elo_opening_suggestion() function.')

    # re-render html page with new table values
    return render_template('stats/elo_opening_suggestion.html')


@stats_blueprint.route('/_update_opening_suggester_table', methods=['GET', 'POST'])
def update_opening_suggester_table():
    skill = int(list(request.args.values())[0])
    novelty = int(list(request.args.values())[1])
    white_value = list(request.args.values())[2] == 'true'

    # get new dataframe based on new elo value
    if white_value:
        df = app.uf.get_ad_recommend_w(skill, novelty)
    else:
        df = app.uf.get_ad_recommend_b(skill, novelty)

    # return the new table out to the client
    return pd.DataFrame(df).to_json(orient='columns')


@stats_blueprint.route('/_opening_suggester_page', methods=['GET', 'POST'])
def opening_suggester_page():
    current_app.logger.info('Calling the opening_suggester_page() function.')

    # re-render html page with new table values
    return render_template('stats/opening_suggester.html')


@stats_blueprint.route('/', methods=['GET', 'POST'])
def index():
    current_app.logger.info('Calling the index() function.')

    # re-render html page with new table values
    return render_template('stats/elo_opening_suggestion.html')

project/stats/templates/stats/elo_opening_suggestion.html
{% extends "stats/index.html" %}

{% block styling %}
{% endblock %}

{% block deepContent %}
    <div class="container">

        <!-- Navbar-->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Meta-Pawn</a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{{ url_for('stats.elo_opening_suggestion') }}">Opening Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_suggester_page') }}">Advanced Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_explorer') }}">Opening Explorer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.png_plot') }}">Top Openings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="content-text">
            <h1><strong>Opening Suggestion</strong></h1>
            <p>This page displays a table with the top openings for the given user input elo.</p>
        </header>

        <body>
        <!-- Display header with dynamically updating elo value -->
        <h3 id="eloHeader">Select an elo:
            <output id="eloOutput">1500</output>
        </h3>
        <input type="range" class="form-range" min="1300" max="2000" step="100" id="eloInputRange">

        <div class="btn-group" role="group">
            <input type="radio" class="btn-check" name="btn-radio" id="white-btn" autocomplete="off" checked>
            <label class="btn btn-outline-dark" for="white-btn">White</label>

            <input type="radio" class="btn-check" name="btn-radio" id="black-btn" autocomplete="off">
            <label class="btn btn-outline-dark" for="black-btn">Black</label>
        </div>

        <input type="button" class="btn btn-dark" value="Refresh Table" id="refresh_button">

        <!-- Display the dynamically updating table element -->
        <table class="table table-dark table-hover table-striped" id="dynamic_chess_table">
        </table>

        <!-- Script which enables dynamic updating of both header and table with slider value -->
        {% block script %}
            <script>
                {#<!-- This block handles updating the slider value display -->#}
                $(function () {
                    $("#eloInputRange").on('input', function (e) {
                        document.getElementById('eloOutput').innerHTML = e.target.value;
                    });
                });

                <!-- This part updates the table when the refresh button is clicked -->
                $("#refresh_button").on("click", function () {
                    var elo = document.getElementById('eloOutput').innerHTML,
                        whiteStatus = document.getElementById('white-btn').checked;
                    $.ajax({
                        type: 'GET',
                        url: $SCRIPT_ROOT + "/_update_alternative_elo_table",
                        data: {
                            elo,
                            whiteStatus
                        },
                        dataType: 'json'
                    }).then(function (data) {
                        document.getElementById('dynamic_chess_table').innerHTML = refreshHtmlTable(data)
                    });
                });

                {# Generate the innerHTML which represents the new table #}

                function refreshHtmlTable(newTable) {
                    var newInnerHTML = "",
                        cols = Object.keys(newTable);

                    newInnerHTML += "<tr>";
                    for (var i = 0; i < cols.length; ++i) {
                        newInnerHTML += "<th>" + cols[i] + "</th>";
                    }
                    newInnerHTML += "</tr>";

                    newInnerHTML += "<tbody>";
                    for (var i = 0; i < Object.values(newTable[cols[0]]).length; ++i) {
                        {# Skips displaying null rows #}
                        if (newTable[cols[0]][i] == undefined) continue;
                        newInnerHTML += "<tr>";
                        for (var key in newTable) {
                            var cellValue = newTable[key][i];
                            {# round floats for nice display #}
                            if (!isNaN(cellValue) && typeof cellValue == 'number') {
                                {# https://stackoverflow.com/questions/4435170/how-to-parse-float-with-two-decimal-places-in-javascript #}
                                cellValue = parseFloat(cellValue).toFixed(2);
                            }
                            newInnerHTML += "<td>" + cellValue + "</td>";
                        }
                        newInnerHTML += "</tr>";
                    }
                    newInnerHTML += "</tbody>";
                    return newInnerHTML;
                }
            </script>
        {% endblock %}
        </body>
    </div>
{% endblock %}

project/stats/templates/stats/index.html
{% include "base.html" %}

{% block styling %}
{% endblock %}

{% block content %}

    <!-- Child template -->
    {% block deepContent %}
    {% endblock %}

    <footer class="bg-dark text-center fixed-bottom text-lg-start">
        <div class="text-center p-3">
            <a class="text-light" href="https://github.com/AlasdairBennett/meta-pawn">COSC4427 2021 Meta-Pawn Source
                Code</a>
        </div>
    </footer>
{% endblock %}

project/stats/templates/stats/opening_explorer.html
{% extends "stats/index.html" %}

{% block styling %}
{% endblock %}

{% block deepContent %}
    <div class="container">

        <!-- Navbar-->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Meta-Pawn</a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.elo_opening_suggestion') }}">Opening Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_suggester_page') }}">Advanced Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{{ url_for('stats.opening_explorer') }}">Opening Explorer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.png_plot') }}">Top Openings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="content-text">
            <h1><strong>Opening Explorer</strong></h1>
            <p>This table has win rate data on all the openings in the dataset. Explore using the search and ordering
                functionalities at your leisure!</p>
        </header>

        <body>

        <!-- Display the dynamically updating table element -->
        <table class="table table-dark table-hover table-striped" id="dynamic_chess_table">
            <thead>
            <tr>
                {% for column in columns %}
                    <th>{{ column }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for row in rows %}
                <tr>
                    {% for cell in row %}
                        <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <!-- Script which enables searching table -->
        {% block script %}
            <!-- Include necessary CSS and JavaScript for DataTables plugin -->
            <link href="{{ url_for('static', filename='pkg/DataTables/datatables.min.css') }}" rel="stylesheet">
            <script src="{{ url_for('static', filename='pkg/DataTables/datatables.min.js') }}"></script>
            <script>
                $(document).ready(function () {
                    $('#dynamic_chess_table').DataTable();
                });
            </script>
        {% endblock %}
        </body>
    </div>
{% endblock %}

project/stats/templates/stats/opening_suggester.html
{% extends "stats/index.html" %}

{% block styling %}
{% endblock %}

{% block deepContent %}
    <div class="container">

        <!-- Navbar-->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Meta-Pawn</a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.elo_opening_suggestion') }}">Opening Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{{ url_for('stats.opening_suggester_page') }}">Advanced Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_explorer') }}">Opening Explorer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.png_plot') }}">Top Openings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="content-text">
            <h1><strong>Advanced Opening Suggestion</strong></h1>
            <p>This table displays the top 5 openings as recommended by Meta-Pawn's advanced AI engine, based on
                complex user inputs. Skill value range is 1: Beginner (< 1500 elo), 2: Intermediate (1500 to 1700), 3:
                Advanced (>1700 elo). The user's inputs will generate a subset from which the recommendations will be
                selected from. The more the opening is played, the more likely it is to be suggested. In other words,
                users are likely to get the most common openings of their inputs subset. This means that the table of
                openings returned is semi-random.</p>
        </header>

        <body>
        <!-- Display header with dynamically updating elo value -->
        <h3 id="eloHeader">Select a skill value:
            <output id="eloOutput">2</output>
        </h3>
        <input type="range" class="form-range" min="1" max="3" step="1" id="eloInputRange">
        <h3 id="noveltyHeader">Select a novelty value (the higher the novelty, the less frequently the opening is
            played):
            <output id="noveltyOutput">2</output>
        </h3>
        <input type="range" class="form-range" min="1" max="3" step="1" id="noveltyInputRange">

        <div class="btn-group" role="group">
            <input type="radio" class="btn-check" name="btn-radio" id="white-btn" autocomplete="off" checked>
            <label class="btn btn-outline-dark" for="white-btn">White</label>

            <input type="radio" class="btn-check" name="btn-radio" id="black-btn" autocomplete="off">
            <label class="btn btn-outline-dark" for="black-btn">Black</label>
        </div>

        <input type="button" class="btn btn-dark" value="Refresh Table" id="refresh_button">


        <!-- Display the dynamically updating table element -->
        <table class="table table-dark table-hover table-striped" id="dynamic_chess_table">
        </table>

        <!-- Script which enables dynamic updating of both header and table with slider value -->
        {% block script %}
            <script>
                {#<!-- This block handles updating the slider value displays -->#}
                $(function () {
                    $("#eloInputRange").on('input', function (e) {
                        document.getElementById('eloOutput').innerHTML = e.target.value;
                    });
                    $("#noveltyInputRange").on('input', function (e) {
                        document.getElementById('noveltyOutput').innerHTML = e.target.value;
                    })
                });

                <!-- This part updates the table when the refresh button is clicked -->
                $("#refresh_button").on("click", function () {
                    var elo = document.getElementById('eloOutput').innerHTML,
                        novelty = document.getElementById('noveltyOutput').innerHTML,
                        whiteStatus = document.getElementById('white-btn').checked;
                    $.ajax({
                        type: 'GET',
                        url: $SCRIPT_ROOT + "/_update_opening_suggester_table",
                        data: {
                            elo,
                            novelty,
                            whiteStatus
                        },
                        dataType: 'json'
                    }).then(function (data) {
                        document.getElementById('dynamic_chess_table').innerHTML = refreshHtmlTable(data)
                    });
                });

                {# Generate the innerHTML which represents the new table #}

                function refreshHtmlTable(newTable) {
                    var newInnerHTML = "",
                        cols = Object.keys(newTable);

                    newInnerHTML += "<tr>";
                    for (var i = 0; i < cols.length; ++i) {
                        newInnerHTML += "<th>" + cols[i] + "</th>";
                    }
                    newInnerHTML += "</tr>";

                    newInnerHTML += "<tbody>";
                    for (var i = 0; i < Object.values(newTable[cols[0]]).length; ++i) {
                        {# Skips displaying null rows #}
                        if (newTable[cols[0]][i] == undefined) continue;
                        newInnerHTML += "<tr>";
                        for (var key in newTable) {
                            var cellValue = newTable[key][i];
                            {# round floats for nice display #}
                            if (!isNaN(cellValue) && typeof cellValue == 'number') {
                                {# https://stackoverflow.com/questions/4435170/how-to-parse-float-with-two-decimal-places-in-javascript #}
                                cellValue = parseFloat(cellValue).toFixed(2);
                            }
                            newInnerHTML += "<td>" + cellValue + "</td>";
                        }
                        newInnerHTML += "</tr>";
                    }
                    newInnerHTML += "</tbody>";
                    return newInnerHTML;
                }
            </script>
        {% endblock %}
        </body>
    </div>
{% endblock %}

project/stats/templates/stats/placeholder_name.html
{% extends "stats/index.html" %}

{% block styling %}
{% endblock %}

{% block deepContent %}
    <div class="container">

        <!-- Navbar-->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Meta-Pawn</a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.alternative_elo_page') }}">Opening Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_suggester_page') }}">Advanced Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{{ url_for('stats.placeholder_name') }}">Placeholder Name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.png_plot') }}">Top Openings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="content-text">
            <h1><strong>Opening Explorer</strong></h1>
            <p>This table has win rate data on all the openings in the dataset. Explore using the search and ordering
                functionalities at your leisure!</p>
        </header>

        <body>

        <!-- Display the dynamically updating table element -->
        <table class="display" id="dynamic_chess_table" style="width:100%">
            <thead>
            <tr>
                {% for column in columns %}
                    <th>{{ column }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for row in rows %}
                <tr>
                    {% for cell in row %}
                        <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <!-- Script which enables searching table -->
        {% block script %}
            <!-- Include necessary CSS and JavaScript for DataTables plugin -->
            <link href="{{ url_for('static', filename='pkg/DataTables/datatables.min.css') }}" rel="stylesheet">
            <script src="{{ url_for('static', filename='pkg/DataTables/datatables.min.js') }}"></script>
            <script>
                $(document).ready(function () {
                    $('#dynamic_chess_table').DataTable();
                });
            </script>
        {% endblock %}
        </body>
    </div>
{% endblock %}

project/stats/templates/stats/png_plot.html
{% extends "stats/index.html" %}

{% block styling %}
{% endblock %}

{% block deepContent %}
    <div class="container">

        <!-- Navbar-->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Meta-Pawn</a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.elo_opening_suggestion') }}">Opening Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_suggester_page') }}">Advanced Suggestion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('stats.opening_explorer') }}">Opening Explorer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{{ url_for('stats.png_plot') }}">Top Openings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="content-text">
            <h1><strong>Top openings by win count.</strong></h1>
            <p>Select a skill range to get a table with the top 10 openings by win count for that range.</p>
        </header>

        <body>

        <!-- Display the png table -->
        <div class="btn-group" role="group" data-toggle="buttons">
            <input type="radio" class="btn-check" name="btn-radio2" id="beginner-btn" autocomplete="off" checked>
            <label class="btn btn-outline-dark" for="beginner-btn">Beginner</label>

            <input type="radio" class="btn-check" name="btn-radio2" id="intermediate-btn" autocomplete="off">
            <label class="btn btn-outline-dark" for="intermediate-btn">Intermediate</label>

            <input type="radio" class="btn-check" name="btn-radio2" id="advanced-btn" autocomplete="off">
            <label class="btn btn-outline-dark" for="advanced-btn">Advanced</label>
        </div>

        <br>
        <br>

        <div class="btn-group" role="group" data-toggle="buttons">
            <input type="radio" class="btn-check" name="btn-radio" id="white-btn" autocomplete="off" checked>
            <label class="btn btn-outline-dark" for="white-btn">White</label>

            <input type="radio" class="btn-check" name="btn-radio" id="black-btn" autocomplete="off">
            <label class="btn btn-outline-dark" for="black-btn">Black</label>
        </div>

        <br>
        <br>

        <img id="dynamicImg" src="{{ url_for('static', filename='img/beg_whit_cp.png') }}">

        <!-- Script which enables the image to change when the buttons are pressed -->
        {% block script %}
            <script>
                {#<!-- This block handles updating the slider value display -->#}
                $(function () {
                    $("#eloInputRange").on('input', function (e) {
                        document.getElementById('eloOutput').innerHTML = e.target.value;
                    });
                });

                <!-- This part updates the table when the refresh button is clicked -->
                $(document).on("input", function (e) {

                    if (document.getElementById('white-btn').checked) {
                        if (document.getElementById('beginner-btn').checked) {
                            document.getElementById('dynamicImg').src = "{{ url_for('static', filename='img/beg_whit_cp.png') }}";
                        } else if (document.getElementById('intermediate-btn').checked) {
                            document.getElementById('dynamicImg').src = "{{ url_for('static', filename='img/int_whit_cp.png') }}";
                        } else if (document.getElementById('advanced-btn').checked) {
                            document.getElementById('dynamicImg').src = "{{ url_for('static', filename='img/adv_whit_cp.png') }}";
                        }
                    } else if (document.getElementById('black-btn').checked) {
                        if (document.getElementById('beginner-btn').checked) {
                            document.getElementById('dynamicImg').src = "{{ url_for('static', filename='img/beg_blk_cp.png') }}";
                        } else if (document.getElementById('intermediate-btn').checked) {
                            document.getElementById('dynamicImg').src = "{{ url_for('static', filename='img/int_blk_cp.png') }}";
                        } else if (document.getElementById('advanced-btn').checked) {
                            document.getElementById('dynamicImg').src = "{{ url_for('static', filename='img/adv_blk_cp.png') }}";
                        }
                    }

                });
            </script>
        {% endblock %}

        </body>
    </div>
{% endblock %}